### ISSUE TITLE
Apply combinations to all weapons at once

### ISSUE THREAD

**Issue by MarHelmer** [phg49389/drg-weapons-calculator#12]
**Is your feature request related to a problem? Please describe.**
A major QOL upgrade would be an option to apply the top menu combinations to all weapons. This might eat CPU for a bit, but it would save a lot of clicking: I might want to figure out what combination of Gunner weapons offers the highest ideal burst DPS, but that involves up to 16 clicks. With an apply-all feature, that drops to two clicks.

**Describe the solution you'd like**
A clone of the Best Combinations menus is added.  When applying through this menu, the selected best combination will calculate for all 20 models.

**Comment by phg49389** [comment]
Like I mentioned in reply on the Reddit thread, I think that this feature is feasible for `Best Combinations (All)`, but I don't think it would reduce clicks for `Best Combinations (Subset)`. Rather than add a third menu called "Best Combinations", instead I'm going to add a checkbox at the bottom of BC(A) menu that can be toggled on/off to do the calculations for all models in the program in one click.

**Comment by phg49389** [comment]
This feature has been added and will be in the next release. Closing issue.
