### ISSUE TITLE
The Radiance mods for Driller primaries both add area damage, but the DPS calculation doesn't account for it.

### ISSUE THREAD

**Issue by EvanByrd** [phg49389/drg-weapons-calculator#19]
Something I noticed was missing from the tool was the inclusion of the damage that is dealt by the Heat Radiance and Cold Radiance modifications for the CRSPR Flamethrower and Cryo Cannon respectively.

To see the damage dealt by the mods it's fairly simple to test by standing next to a Loot Bug or Glyphid Grunt and hold the trigger for one second while intentionally missing the target. If the bug is within 3 meters of the player it well take 80 Fire Damage from Heat Radiance, or 60 Ice Damage from Cold Radiance. Cold Radiance can extend to 4 meters but has damage falloff starting from 3 meters and will be reduced down to a minimum of 25% damage. Both mods will deal one instance of damage per second regardless of flow rate.

**Comment by phg49389** [comment]
The Heat radiance bug was reported to me yesterday, and I rolled out a fix for it ( see Issue #11 ). I was not aware of the Cold Radiance 60 Frost Damage/sec. I'll implement the same solution that I did for Heat Radiance.

Thanks for letting me know!

**Comment by phg49389** [comment]
I just tested Cold Radiance in-game. It did no damage to enemies without the direct stream; therefore it only does Cold Damage. Not Cold + Frost. Additionally, the wiki only indicates that it does Cold Damage.

When I tested Heat Radiance for Issue #11 it did do damage, so I changed the model accordingly. Cold Radiance is already modeled to decrease the time to freeze enemies proportional to how far the stream reach is, so that functionality is already taken care of.

Since Heat Radiance DPS has already been added for previous bug report, and Cold Radiance doesn't have additional DPS, I'm choosing to close this issue.
