### ISSUE TITLE
[Bug?] Gunner Combat mobility overclock params mismatch

### ISSUE THREAD

**Issue by marcinsmialek** [phg49389/drg-weapons-calculator#35]
The in-game description doesn't say anything about image decrease with Combat Mobility
It's displayed as 14 with and without this overclock

The description also states that:

- Reload time is decreased from 5s to 4s
- Base spread is reduced to 70%

Game build 1.32.46057.0

https://github.com/drg-tools/drg-weapons-calculator/blob/c8fb724fca0d5e916e932de71d3541d4f4c986a9/src/gunnerWeapons/Autocannon.java#L304-L306

If the data in calculator is accurate, and displayed in game is not, how did you mine the values?

**Comment by phg49389** [comment]
Hey @marcinsmialek , thanks for the bug report! Combat Mobility was changed significantly in U32. It used to have a -2 Direct Damage penalty in U31. If you look at the top of the window it should say that the version you're using was compiled for U31.5. I have been waiting for GSG to finish pushing out hotfixes for U32 before I release the new Calculator version. When I do, those new Combat Mobility stats should match the game again.

I'll send another comment on this issue once the new version is released so that you can take a look at the new stats 👍

**Comment by phg49389** [comment]
@marcinsmialek Fulfilling my promise: here's a link to the new release of the DPS Calculator that has U32's balance changes. Download and install this version and you should be able to see the updated Combat Mobility just fine.

https://github.com/drg-tools/drg-weapons-calculator/releases/tag/v1.0.6

Closing issue.
